# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67562d923afea33937e75261adc11e4ee3f294bce933c2c3f812824b3721047dc04cf1de7b57229e28b8ca3ee9b06fe94a9edaab4423cae5d8ca3aabac6b8771

test:
  secret_key_base: 12250bfa4fc384845b9d0e9e0daabac1732b5b104f87f22f8bc0470d17daa0140f13f1ca4c8af26044a97868a777d51d668620252bff7406d8a7ef9bb6ba0d95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
